### ISSUE TITLE
Change order of values not possible

### ISSUE THREAD

**Issue by DJay-X** [skrollme/homebridge-eveatmo#12]
I noticed that I can’t change the order of some values in Eve App.
In the enclosed example I noticed this with the values of the outdoor sensor only. I want to set value temperature on top but it doesn’t work. 

![d522a427-5e79-4fd7-b4da-5222ff6f0fea](https://user-images.githubusercontent.com/3874239/37557240-f3638cfc-2a01-11e8-8203-b7afb9e5ceb8.gif)

**Comment by skrollme** [comment]
Same here, but - as far as I know - I did not do anything which should cause this :D 
Did you find any reports if this behavior also occurs with a real EVE Weather?

**Comment by DJay-X** [comment]
Sorry for the late response.
I checked all the native eve sensors and there is no such behavior to notice.

What I can see is that the problem with the netatmo sensors only is with the outdoor module.
I have a frieds netatmo station also connected and in all rooms I can change the order except the outdoor. Air Pressure "Luftdruck" is always first and moving for example the temperature on top is just ignored.

**Comment by skrollme** [comment]
Thanks for the feedback. So this problem only occurs with the homebridge-eveatmo plugin, not with a real Eve Weather or Room. I will look into this

**Comment by skrollme** [comment]
Hey @DJay-X 
every now and then I looked at it and hoped that maybe an eve-update would resolve this but that did not happen so far. I just played a bit around and added an extra co2-characteristic to the accessories. This will be displayed in the stock-home.app and also in the eve.app but it can be hidden there if needed. 
While testing I noticed that reordering this new co2-characteristic is even worse in the eve-app. The app often crashes immediately while trying this, so I think this whole problem is some kind of bug of the eve-app. Maybe it just occurs because the faked eve-accessory, but I still not had access to real eve-modules. 
So I'm afraid we will not make some progress here in the near future, but I will keep this issue open to remind me checking again now and then.

**Comment by DJay-X** [comment]
Thanks @skrollme I do the same "every now and then I looked at it and hoped that maybe an eve-update would resolve this" ;)

I have a Eve Weather and a Netatmo Sensor in the same Room "Balkon".
Sorting the Eve Categories "Temperatur, Luftfeuchtigkeit, Luftdruck" works like expected. 
Doing the same with the Netatmo sensor, it's not possible. 
Still a mystery. ;)  But thanks again for keeping it in mind.


![Netatmo-Eve](https://user-images.githubusercontent.com/3874239/57200971-614f3500-6f92-11e9-9927-413eacaf051c.gif)

**Comment by skrollme** [comment]
Hey @DJay-X , after the last eve.app update this seems to be fixed for me. What about you?
