### ISSUE TITLE
Firmware-Update showing up

### ISSUE THREAD

**Issue by DJay79** [skrollme/homebridge-eveatmo#2]
First of all thanks for this great plugin. Love it and works good with my first try.
Using Netatmo Rain Sensor and a few indoor and outdoor Sensors.
What I was wondering is that the Eve App is showing a Firmware-Update for Version 1.3.1 (466) for the 8 Devices added by homebridge-eveatmo.
Any chance to get rid of this?

Thanks again und viele Grüße. ;)

**Comment by skrollme** [comment]
I'm seeing this by myself but for the beginning it tried to change as little as possible from the current known state about the protocol. I will try to fix this in one of the next updates

**Comment by simont77** [comment]
It should be due to the characteristic E863F11E. I saw the same behavior with the fake accessory I user for history experiments. I did not find any other useful use for that characteristic.

**Comment by skrollme** [comment]
thanks, @simont77. I will give it a try.

**Comment by skrollme** [comment]
Please check out the newest release 0.2.4, @DJay79. It is already on NPMJS, so `(sudo) npm install -g homebridge-eveatmo`should do it.

**Comment by DJay79** [comment]
@skrollme Thanks a lot. Version 0.2.4 works for me. No asking for Firmware-Update anymore. Great! 👍🏻
Any chance to see Netatmo Thermostat working with your plugin in the near future? This is now the only reason why I still use homebridge-netatmo.

Thanks again for your work and sharing.

**Comment by skrollme** [comment]
> Thanks a lot. Version 0.2.4 works for me. No asking for Firmware-Update anymore. Great! 👍🏻

Great to hear that!

> Any chance to see Netatmo Thermostat working with your plugin in the near future? This is now the only reason why I still use homebridge-netatmo.

I do not own a thermostat by myself so it has no real priority for me at the moment. My next goal is to get the history service running and some refactoring because the plugin seems to call the API more often than it should. This can easily lead to soft-bans at the Netatmo API, if you restart Homebridge too often.
So for the moment I would suggest you use the homebride-netatmo and limit it to the thermostat via config. But feel free to add add a new Issue here for this topic. It won't get forgotten ;)
