### ISSUE TITLE
Using windsensor data for opening raffstore

### ISSUE THREAD

**Issue by marcoxedge** [skrollme/homebridge-eveatmo#30]
Hello,
I am a absolute beginner and just bought a raspi, so sorry for any dumb questions.

I'd like to have all my smarthome functionalities in Apple HomeKit. Unfortunatelly a lot of components do not support HomeKit. One of these is the weatherstation from Netatmo.
That's how I landed here.

In case of exceeding certain wind speeds the raffstores have to open in order to protect them from any damage.

Is this already possible to set via homebridge and your eveatmo plugin ?
Do I have to use any other hardware from netatmo than the weatherstation itself?
Do I need any other software on my iPhone than HomeKit? 

Thank you a lot.

**Comment by skrollme** [comment]
Hello

> In case of exceeding certain wind speeds the raffstores have to open in order to protect them from any damage. In case of exceeding certain wind speeds the raffstores have to open in order to protect them from any damage.

Because I do not own the netatmo-windsensor by myself I did not setup it by myself and I'm not sure if this kind of automations will work.

> Do I have to use any other hardware from netatmo than the weatherstation itself?

If you set up homebridge on your pi you only need the netatmo-basestation. The homebridge-plugin fetches the weatherdata from the netatmo-servers. if you want to access your HomeKit devices from outside your local-network, you need an AppleTV or an iPad which will work as a local-to-internet-bridge for HomeKit

> Do I need any other software on my iPhone than HomeKit?

Apple's HomeKit app (Home.app) will do it in most case. But you can try others like Eve.app

But maybe you wait a little bit, it seems that Netatmo announced nativ HomeKit support for the basestation, at least if you own the hardware-revision v3 of the basestation.
See: https://www.reddit.com/r/HomeKit/comments/dd61lf/netatmo_weather_station_homekit_support_coming/
