### ISSUE TITLE
Seemingly silent fails brings down homebridge

### ISSUE THREAD

**Issue by ntableman** [skrollme/homebridge-eveatmo#35]
With the recent update this plug in causes my entire set of home bridge devices to fail in HomeKit. I have turned on debug and tried to find ways for this to work, but so far I cannot figure out any information to share.

I know it is this plugin because I removed all my platforms in the config and put them back in 1:1 and this one is the one which causes the issue.

Any ideas on how to help debug?

**Comment by skrollme** [comment]
Hello @ntableman , I'm sorry for this, I tried the exact same code for a fews days before releasing and had no problems so far. Current measurements and history work like expected.

Concerning debugging: Homebridge should print out error-messages or exceptions when crashing. You could also try to start it without deamonization in a terminal and see when/how it fails.

**Comment by ntableman** [comment]
Sure, just making sure others are aware this plugin can bring their Homebridge to a halt, even when used alone. I happened in the prior version as well, which is why I updated it.

I trolled the logs: there isnt an error being kicked out, even if Homebridge is in debug mode.

**Comment by skrollme** [comment]
Hey @ntableman , please check out the just published version 0.4.10 at let me know if it helped

**Comment by Phoenix-DH** [comment]
Already tried the latest version?

**Comment by shnhrrsn** [comment]
Yeah, this is a super strange issue.  Based on the logs everything looks fine.  Eveatmo and other platforms/plugins I have all look to boot up and “work”, they log accessories they’ve detected and such.  Homebridge itself thinks it’s working, QR code prints, etc.

However, once I go to Home.app, nothing works, accessories say they’re not responding, when I try to trigger one nothing happens.  As soon as I disable evatmo, everything works again.

**Comment by Phoenix-DH** [comment]
Really strange ... I tried this version... all good.

**Comment by lisanet** [comment]
I ran into the same issue and took a look at the code. AFAICS eveatmo uses netatmo.js module to request data from the Netatmo servers. This request function has no timeout and may wait forever until Netatmo servers answer, either with data or with an error. And because eveatmo uses callbacks it will block execution until this request will finish.

I've done a quick test by adding a timeout value to netatmo.js module and everything works fine, so it seems to me that this is the cause of this misbehavior. 

Since eveatmo can not change the netatmo.js code, a IMO better approach to fix this issue is to use a more event driven code in eveatmo and not using callbacks. The netatmo.js module supports  in every function by emitting an appropriate signal / event. Of course, using event will need more or less rewriting of the eveatmo code.

I'll have look at he code and see if I can change eveatmo to act in an event driven way.

**Comment by skrollme** [comment]
Hello @lisanet , I agree that there is definitely be a better (and cleaner) way to make this plugin working. This plugin was based on another plugin and it was my first nodeJs project... just to put some excuses on the table ;) 

Because I have very little problems with the current codebase (and a stable internet connection at home) I currently do not plan to do an overhaul by myself.

I have also looked into the netatmo.js (the npm dependency) some time ago and still have an open Issue at this project (https://github.com/karbassi/netatmo/issues/36). I did not find a good way to change the eveatmo's plugin logic without changes at the netatmo.js but - as I said - I'm a nodeJS noob.

If you are willing to participate here, I'm happy with it :) I could also add you as a contributor to this project if this will help you

**Comment by lisanet** [comment]
As I said, I'll have a look at the code and try to make more robust if netatmo servers won't answer.

I read your issue on netatmo.js too. But IMO your proposal is of no use. If you use external http requests to get some data, you should not wait in  a synchronous way for the answer as this will block execution of the code until the server answers. This is the case with your code, cause you'reusing callbacks when invoking getStationData(). So eveatmo gets blocked and therefor also homebridge as a whole gets blocked, because netatmo servers don't answer.

Using http request should be done async. netatmo.js does this by emitting a signal when the the requests get answered. Changing your code to add a listener to this signal will solve this issue. Of course this will need more or less rewriting portions of your code, especially code for creating the accessories at startup.

**Comment by skrollme** [comment]
@ntableman: New update with some fixed from @ lisanet is out since yesterday. Please give it a try and let me us know if you experience some differences

**Comment by skrollme** [comment]
> As I said, I'll have a look at the code and try to make more robust if netatmo servers won't answer.
> 
> I read your issue on netatmo.js too. But IMO your proposal is of no use. If you use external http requests to get some data, you should not wait in a synchronous way for the answer as this will block execution of the code until the server answers. This is the case with your code, cause you'reusing callbacks when invoking getStationData(). So eveatmo gets blocked and therefor also homebridge as a whole gets blocked, because netatmo servers don't answer.
> 
> Using http request should be done async. netatmo.js does this by emitting a signal when the the requests get answered. Changing your code to add a listener to this signal will solve this issue. Of course this will need more or less rewriting portions of your code, especially code for creating the accessories at startup.

As mentioned above, I would be grateful for every PR, but because the current state works for me and I have almost no problems (except on longer Netatmo API outages) I do not plan to start a refactor in the near future.

**Comment by sonicpixel2020** [comment]
I have exactly the same problem in Hoobs. I was going back to v0.4.8. This version is running without that issue.

**Comment by skrollme** [comment]
@sonicpixel2020 Can you confirm that all your Netatmo-accessories are reachable on homebridge-startup? You can check this here for example, if you are logged in into your account:
https://dev.netatmo.com/apidocumentation/weather#getstationsdata

**Comment by hajanet** [comment]
I ran into this issue too today.
Therefore I have fully recovered my whole raspi and my whole configuration.

My Setup looks like: homebridge-ui, homebridge-hue with deconz connected.

Now, while installing and reconfiguring the whole setup, all crashed again after installing 0.5.0 of eveatmo-plugin.
I've then tried different things.
I've tried to go down with the version: no change.
I've then unplugged and plugged the netatmo-station.
After that, I've done a restart of homebridge and then it worked!

That should not happen. If the plugin ran into an exception it should not make homebridge stop working.
I've analyzed what happens when the bug occurs. Changes of all hue-devices are still transmitted to homebridge. I can see them in the logfiles. But there seems to be no connection with the Home-App (or Eve). All devices are with "No response" in the app.

Maybe you've changed something with the exception-handling or there is no effective exception-handling. But there should be. I'm not an expert with Node.js too; but I guess it should be possible.

Thanks for your engagement.

**Comment by sonicpixel2020** [comment]
> @sonicpixel2020 Can you confirm that all your Netatmo-accessories are reachable on homebridge-startup? You can check this here for example, if you are logged in into your account:
> https://dev.netatmo.com/apidocumentation/weather#getstationsdata

I do not know exactly what you mean. But after I did an update to hoobs 3.1.20, the plugin is working.

**Comment by hajanet** [comment]
I can't guarantee that.
But, this is the big point, the homebridge-plugin should not stop all others from working, if the netatmo-station is not reachable.

**Comment by hajanet** [comment]
Update: I've now resetted my eveatmo to 0.4.8 as this is the last version which is really working with my setup.

Regards

**Comment by skrollme** [comment]
Hello @hajanet ,
I'm sorry to hear that and I agree with you that this should not happen but I also do not know how this could happen. I have no problems with the current state (and the previous state before 0.4.9). The changes in 0.4.9 were only made because of some people had problems; now other people have different problems.
Because this is a hobby project for me I do not plan to put hours or weeks into debugging this because there are so many possible setups and environments which homebridge can run into.
If you are fine with 0.4.8 stay on this version, if you want the new features (there are not any real/new features now nor planed) fork this project, start from 0.4.8 and cherrypick the commits you like.

**Comment by th3cube** [comment]
Something after 0.4.8 completly messed up my homebridge. took me hours to find out that eveatmo plugin was the problem. after removing eveatmo everything worked again.
