### ISSUE TITLE
Battery Indicator

### ISSUE THREAD

**Issue by 2Qt2beStr8** [skrollme/homebridge-eveatmo#46]
Hi,
would it be possible to implement separate switches for the battery indicator in the home app?  In Homebridge, these switches are already displayed at the devices

best regards
DJ

![E9592EC0-2997-4FDC-A202-791410C64918](https://user-images.githubusercontent.com/20930745/98442134-2b4cbd00-2103-11eb-8273-176efa60bee1.jpeg)

**Comment by skrollme** [comment]
I'm not really sure what you exactly want :D Where does this screenshot from? I do not use this app/tool. I'm using Apple's default Home.app and the third-party EVE.app, and I see no separate "Battery-items".

**Comment by 2Qt2beStr8** [comment]
This screenshot comes from the Homebridge UI. I know that this Switches are not visible in Apple‘s default Home.app — i see them only on the Homebridge UI Webinterface.

**Comment by skrollme** [comment]
Hello @2Qt2beStr8 ,
the battery-services are implemented in a default way, so that they are displayed in HomeKit apps on their proposed places/menus. I'm not planning to remove them or to add switches. If you do not want to see certain services in HomebridgeUI this would be a filter-functionality for HomebridgeUI.
But you are also free to fork this plugin and/or make a pull request to implement this feature by yourself.
