### ISSUE TITLE
Eveatmo breaks homebridge if Netatmo Weather does not connect

### ISSUE THREAD

**Issue by Marfre888** [skrollme/homebridge-eveatmo#49]
Hi,

I'm runninng into a problem with the Eveatmo plugin. Presently my Netatmo weather station for some reason was failing to correctly find the Wifi signal and connect to it. However I seem to have fixed that now.

Problem I'm having with the Eveatmo plugin, is that if the Netatmo weather station is offline, it will prevent homebridge from running, the log reports that the plugin failed to talk to nentatmo, and keeps doing this indefinitely.

Is there a way the plugin could timeout after a number of tries, and report the tiles as no response, allowing homebridge to run?

Thanks

**Comment by skrollme** [comment]
We had similar reports here in the past. For example in this issue: https://github.com/skrollme/homebridge-eveatmo/issues/39
As written there, I tested many cases by myself but I never got these kind of problems. So at some point in time I stopped researching in this direction because I had no chance to reproduce this. My setup even worked while real Netatmo-API outages.

If you have the ambitions to research this problem, feel free to do it. Pull requests to this plugin are always welcome.
