### ISSUE TITLE
Integration of public Netatmo Weather Stations from neighbors ?

### ISSUE THREAD

**Issue by GDeb59** [skrollme/homebridge-eveatmo#50]
Hello team,

I have also some neighbors with Netatmo stations.

I'm not developer but it should be amazing if :
- we can collect data from a Netatmo weather station with method : /getpublicdata
- store them with fakegato-history package (https://www.npmjs.com/package/fakegato-history) to see datas on EVE app

It will be a virtual weather Netatmo station.

Thanks for help,
Guillaume

**Comment by skrollme** [comment]
If your neighbors share their Netatmo data via the share function the platform already has this is possible. I've already tried this with a colleague. But I think this way will share all the data, not only the outdoor sensor which could be a privacy issue :D 

In general a good idea, but at the moment I do not plan to integrate larger features, because this is now only a side-project for me and I just try to keep it (more or less) running.

**Comment by GDeb59** [comment]
With an account on Netatmo API website and this method : https://dev.netatmo.com/apidocumentation/weather#getpublicdata
I can retrieve values from 3 neighbors's stations in my zone so really cool.

I found another homebridge plugin, still in development but dev seems to be stopped : 
https://github.com/antoninbiret/Homebridge-Netatmo-Weather-Station

I use EVE room and EVE app + Apple Home app.
With EVE app it's very useful to have historical datas from temp/humidity/air quality.

I think if I have neighbors with Netatmo stations I don't need to buy it :-)

For now I'm using Hoobs + plugin weatherplus with darsky service to have a virtual weather station but I think it's better to have a real weather station.

**Comment by skrollme** [comment]
As I said, I do not plan to add this in the near future. If you want to try it by yourself, feel free. Pull requests are always welcome.
Otherwise I would close this issue.

**Comment by GDeb59** [comment]
Ok thanks skrollme.

I close this feature request.
